name: Go CI with go

on:
  push:
    paths:
      - 'go/**/*.go'
  pull_request:
    paths:
      - 'go/**/*.go'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.17", "1.19", "1.20", "1.21.x"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go Tests
        run: |
          cd ./go
          go test ./...
