name: Java CI with Maven

on:
  push:
    paths:
      - 'maven_java/**/*.java'
  pull_request:
    paths:
      - 'maven_java/**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17, 21]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'

    - name: Run mvn test
      run: mvn -B test --file ${{ github.workspace }}/maven_java/pom.xml

